### ISSUE TITLE
npm run prod is failing

### ISSUE THREAD

**Issue by justinsisley** [justinsisley/mercenary#18]
`child_process.js:532
    throw err;
    ^

Error: Command failed: 
    rm -rf /Users/manmademammal/projects/playground/test-app/static &&
    NODE_ENV=production "/Users/manmademammal/projects/playground/test-app/node_modules/.bin/webpack"       --display-error-details       --config       "/Users/manmademammal/projects/playground/test-app/node_modules/mercenary-core/config/webpack/production.js"
  
    at checkExecSyncError (child_process.js:489:13)
    at Object.execSync (child_process.js:529:13)
    at build (/Users/manmademammal/projects/playground/test-app/node_modules/mercenary-core/tasks/build.js:10:6)
    at Object.<anonymous> (/Users/manmademammal/projects/playground/test-app/node_modules/mercenary-core/index.js:49:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)`

**Comment by justinsisley** [comment]
Issue caused by webpack's UglifyJS plugin not supporting ES2015 at all. Solution was to change babel-preset-env to support all browsers with greater than 1% share, meaning ES2015 is transpiled to ES5.
